### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by omoses43** [documenso/documenso#1307]
Not receiving a reset password email or an email to confirm my account

**Comment by Dvalin21** [comment]
> Not receiving a reset password email or an email to confirm my account

I've been having that same issue. I haven't gotten a response here or discord

**Comment by illia-stv** [comment]
Same problem😪

**Comment by illia-stv** [comment]
Alright, I have just downloaded [MailHog](https://github.com/mailhog/MailHog) (an email testing tool) and run it. By default, it runs on `0.0.0.0:1025`, so you just need to set `NEXT_PRIVATE_SMTP_HOST="0.0.0.0"` and `NEXT_PRIVATE_SMTP_PORT=1025` in the .env file. Then, you can catch the confirmation email in the MailHog web app, which runs on `127.0.0.1:8025`. That’s how I solved the problem for myself.

**Comment by Dvalin21** [comment]
> Alright, I didn't have a SMTP server so I needed to just downloaded [MailHog](https://github.com/mailhog/MailHog) (an email testing tool) and run it. By default, it runs on `0.0.0.0:1025`, so you just need to set `NEXT_PRIVATE_SMTP_HOST="0.0.0.0"` and `NEXT_PRIVATE_SMTP_PORT=1025` in the .env file. Then, you can catch the confirmation email in the MailHog web app, which runs on `127.0.0.1:8025`. That’s how I solved the problem for myself.

I may have to try that. Its just crazy you have to go around about way to just to get it to send an email to confirm your account.

**Comment by ephraimduncan** [comment]
If you're not receiving reset password emails or account confirmation emails, run `npm run d` in your terminal. This will starts the necessary services, including the email server with `Inbucket`. 

Once running, you can access the incoming mail server at `http://localhost:9000/`. Check this interface to see if the reset password and account confirmation emails are being processed correctly.

**Comment by ephraimduncan** [comment]
@parasiteoflife Can you try running `npm run reset:hard && npm run d` and still see if the issue persists?

**Comment by JokoBurger** [comment]
I'm having the same issue, that no verification mail is sent out. (Docker compose installation & SMTP credentials are correct).
The logs are non really helping. (Also tried using npm run dx && npm run dev) 

I already have port 9000 in use on the host. Is there a way to access the SMTP UI on another port? 

**Logs**:
`2024-09-28T15:27:43.822369742Z Eligible jobs: [ 'Send Confirmation Email' ]
2024-09-28T15:27:43.917264804Z Submitting job to endpoint: http://192.168.178.148:4701/api/jobs/send.signup.confirmation.email/****
2024-09-28T15:27:43.929658265Z [JOBS]: Triggering job send.signup.confirmation.email with payload { email: 'name@mymail.de' }
2024-09-28T15:27:44.918459761Z [JOBS]: Job send.signup.confirmation.email failed Error: Failed to send the confirmation email
2024-09-28T15:27:44.918630369Z     at u (/app/apps/web/.next/server/chunks/9783.js:1:31543)
2024-09-28T15:27:44.918687989Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-28T15:27:44.918742879Z     at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:19365)
2024-09-28T15:27:44.918777728Z     at async /app/apps/web/.next/server/chunks/9783.js:1:15444
2024-09-28T15:27:44.918810878Z     at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
2024-09-28T15:27:44.918852168Z     at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
2024-09-28T15:27:44.918888408Z     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
2024-09-28T15:27:44.918931287Z     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
2024-09-28T15:27:44.918968097Z     at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:816:17)
2024-09-28T15:27:44.919001997Z     at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:174:21)
2024-09-28T15:27:44.936032365Z Submitting job to endpoint: http://192.168.178.148:4701/api/jobs/send.signup.confirmation.email/cm1mb2zvi0002nq2nlv4y5p6r
2024-09-28T15:27:44.945276959Z [JOBS]: Triggering job send.signup.confirmation.email with payload { email: 'name@mymail.de' }
`

Thanks in advance! :)

**Comment by JokoBurger** [comment]
I tried the adjustment and redeployed the containers but the issue still persists.
Can you share the complete environment settings?

I also tested my Mailserver and it's working.

**Comment by Dvalin21** [comment]
Exactly the error I would get, but with trying to send using gmail instead

**Comment by JokoBurger** [comment]
Thanks for the env vars! 
Also tried it and also using single quotes around all all variables. Everything else in configured the same way but still same error message

**Comment by RosaEinhorn** [comment]
I am having the same issue. Mails are not sent. There is no error in the logs, it just says:
```
Submitting job to endpoint: http://host:3000/api/jobs/send.signup.confirmation.email/cm23benwk0000qo28te6x1sjf
```
Any idea on how to further debug the mail config?

**Comment by Dvalin21** [comment]
> I am having the same issue. Mails are not sent. There is no error in the logs, it just says:
> 
> ```
> Submitting job to endpoint: http://host:3000/api/jobs/send.signup.confirmation.email/cm23benwk0000qo28te6x1sjf
> ```
> 
> Any idea on how to further debug the mail config?

From what I can see we can't get any further logs as we can remote into the container. I deleted my last comment as I put the wrong issue in the wrong post. I've been getting the same issue. Says sent, but no email received and no error logs.

**Comment by Dvalin21** [comment]
> NEXT_PRIVATE_INTERNAL_WEBAPP_URL

Tried this tonight, still not working for me.

**Comment by Dvalin21** [comment]
> Finally got it to work with real SMTP server, you don't need to run dev.
> 
> In the env variables `NEXT_PRIVATE_INTERNAL_WEBAPP_URL` should be set to your public URL, so same as `NEXT_PUBLIC_WEBAPP_URL`, using localhost and port doesn't work. Also, using `NEXT_PRIVATE_SMTP_PORT="465"` and `NEXT_PRIVATE_SMTP_SECURE="true"` doesn't work either, you have to use STARTTLS (port 587) and set that env to false.

After a little more changing, I got something a little different than before. Instead of getting the "Submitting job to endpoint: http://localhost:port/api/jobs/send.signup.confirmation.email/whatever it is" I got "NEXT_PUBLIC_MARKETING_URL=/api/jobs/send.signup.confirmation.email/whatever it is"  What do you have for your NEXT_PUBLIC_MARKETING_URL?

**Comment by RosaEinhorn** [comment]
It is set as in the [example compose](https://raw.githubusercontent.com/documenso/documenso/release/docker/production/compose.yml):
```
- NEXT_PUBLIC_MARKETING_URL=${NEXT_PUBLIC_MARKETING_URL:-https://documenso.com}
```

**Comment by Dvalin21** [comment]
> It is set as in the [example compose](https://raw.githubusercontent.com/documenso/documenso/release/docker/production/compose.yml):
> 
> ```
> - NEXT_PUBLIC_MARKETING_URL=${NEXT_PUBLIC_MARKETING_URL:-https://documenso.com}
> ```
> 
> and I have no value in my .env, so it should be https://documenso.com I guess.

Correct, but after making a few changes its the first time that I've seen it being mentioned in my logs. So I thought possibly there was another config for it in the compose and in the env

**Comment by Dvalin21** [comment]
Found my first error Error: No session found
documenso-app  |     at c (/app/apps/web/.next/server/chunks/2912.js:1:1190205)

**Comment by Dvalin21** [comment]
> Finally got it to work with real SMTP server, you don't need to run dev.
> 
> In the env variables `NEXT_PRIVATE_INTERNAL_WEBAPP_URL` should be set to your public URL, so same as `NEXT_PUBLIC_WEBAPP_URL`, using localhost and port doesn't work. Also, using `NEXT_PRIVATE_SMTP_PORT="465"` and `NEXT_PRIVATE_SMTP_SECURE="true"` doesn't work either, you have to use STARTTLS (port 587) and set that env to false.

Can you share your complete .env setup?  Thanks

**Comment by Dvalin21** [comment]
> Maybe your env file is not being used. What are you using? Portainer or plain compose file? Also better nuke your current installation (remove the db volume/data) before re-deploying
> 
> I'm using Portainer:
> 
> Compose file (I'm not linking any ports because NPM access documenso through the docker network):
> 
> ```yaml
> services:
>   documenso-db:
>     image: postgres:15
>     container_name: documenso-db
>     healthcheck:
>       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
>       interval: 10s
>       timeout: 5s
>       retries: 5
>     env_file: stack.env
>     volumes:
>       - type: bind
>         source: /documenso/database
>         target: /var/lib/postgresql/data
>         read_only: false
>     networks:
>       documenso:
> 
>   documenso:
>     image: documenso/documenso:latest
>     container_name: documenso
>     depends_on:
>       documenso-db:
>         condition: service_healthy
>     env_file: stack.env
>     #ports:
>     #  - 3000:3000 #normal
>     #  - 3001:3001 #marketing
>     volumes:
>       - type: bind
>         source: /documenso/certificate.p12
>         target: /cert-file/certificate.p12
>         read_only: true
>     networks:
>       documenso:
>       npm:
>   
>   documenso-minio:
>     image: minio/minio:latest
>     container_name: documenso-minio
>     #ports:
>     #  - 9002:9002 # server
>     #  - 9001:9001 # console
>     volumes:
>       - type: bind
>         source: /documenso/minio
>         target: /data
>         read_only: false
>     env_file: stack.env
>     command: server /data --console-address ":9001" --address ":9002"
>     networks:
>       documenso:
> 
> networks:
>   documenso:
>     name: documenso
>     driver: bridge
>   npm:
>     name: npm
>     external: true
> ```
> 
> ```dotenv
> # [[AUTH]]
> NEXTAUTH_URL="https://documenso.domain.io"
> NEXTAUTH_SECRET='long-password-1'
> 
> # [[CRYPTO]]
> # Application Key for symmetric encryption and decryption
> # REQUIRED: This should be a random string of at least 32 characters
> NEXT_PRIVATE_ENCRYPTION_KEY='long-password-2'
> # REQUIRED: This should be a random string of at least 32 characters
> NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY='long-password-3'
> 
> # [[AUTH OPTIONAL]]
> # Find documentation on setting up Google OAuth here:
> # https://docs.documenso.com/developers/self-hosting/setting-up-oauth-providers#google-oauth-gmail
> #NEXT_PRIVATE_GOOGLE_CLIENT_ID=""
> #NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=""
> 
> #NEXT_PRIVATE_OIDC_WELL_KNOWN=""
> #NEXT_PRIVATE_OIDC_CLIENT_ID=""
> #NEXT_PRIVATE_OIDC_CLIENT_SECRET=""
> #NEXT_PRIVATE_OIDC_PROVIDER_LABEL="OIDC"
> # This can be used to still allow signups for OIDC connections
> # when signup is disabled via `NEXT_PUBLIC_DISABLE_SIGNUP`
> #NEXT_PRIVATE_OIDC_ALLOW_SIGNUP=""
> #NEXT_PRIVATE_OIDC_SKIP_VERIFY=""
> 
> # [[URLS]]
> NEXT_PUBLIC_WEBAPP_URL="https://documenso.domain.io"
> NEXT_PUBLIC_MARKETING_URL="https://documenso-marketing.domain.io"
> # URL used by the web app to request itself (e.g. local background jobs)
> # This can't be localhost:3000, it doesn't work, you have to use the public URL instead.
> NEXT_PRIVATE_INTERNAL_WEBAPP_URL="https://documenso.domain.io"
> 
> # [[DATABASE]]
> NEXT_PRIVATE_DATABASE_URL='postgres://documenso:LONG-PASSWORD-4@documenso-db:5432/documenso'
> # Defines the URL to use for the database when running migrations and other commands that won't work with a connection pool.
> NEXT_PRIVATE_DIRECT_DATABASE_URL='postgres://documenso:LONG-PASSWORD-4@documenso-db:5432/documenso'
> 
> POSTGRES_USER="documenso"
> # This password shouldn't contain special characters like '%', '$' or '@' to avoid issues.
> POSTGRES_PASSWORD='LONG-PASSWORD-4'
> POSTGRES_DB="documenso"
> 
> # [[SIGNING]]
> # The transport to use for document signing. Available options: local (default) | gcloud-hsm
> NEXT_PRIVATE_SIGNING_TRANSPORT="local"
> # OPTIONAL: The passphrase to use for the local file-based signing transport.
> NEXT_PRIVATE_SIGNING_PASSPHRASE='p12-cert-password'
> # OPTIONAL: The local file path to the .p12 file to use for the local signing transport.
> NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH="/cert-file/certificate.p12"
> # OPTIONAL: The base64-encoded contents of the .p12 file to use for the local signing transport.
> NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS=
> # OPTIONAL: The path to the Google Cloud HSM key to use for the gcloud-hsm signing transport.
> NEXT_PRIVATE_SIGNING_GCLOUD_HSM_KEY_PATH=
> # OPTIONAL: The path to the Google Cloud HSM public certificate file to use for the gcloud-hsm signing transport.
> NEXT_PRIVATE_SIGNING_GCLOUD_HSM_PUBLIC_CRT_FILE_PATH=
> # OPTIONAL: The base64-encoded contents of the Google Cloud HSM public certificate file to use for the gcloud-hsm signing transport.
> NEXT_PRIVATE_SIGNING_GCLOUD_HSM_PUBLIC_CRT_FILE_CONTENTS=
> # OPTIONAL: The path to the Google Cloud Credentials file to use for the gcloud-hsm signing transport.
> NEXT_PRIVATE_SIGNING_GCLOUD_APPLICATION_CREDENTIALS_CONTENTS=
> 
> # MINIO
> 
> # This one is commonly used in URLs so use special characters with care or only use letters, numbers, "." and "_".
> MINIO_ROOT_USER="random-chars-1"
> MINIO_ROOT_PASSWORD='long-password-5'
> MINIO_API_CORS_ALLOW_ORIGIN="https://documenso.domain.io"
> MINIO_SITE_REGION="wx-east-1"
> MINIO_OPTS="--console-address :9001 --address :9002"
> 
> # [[STORAGE]]
> # OPTIONAL: Defines the storage transport to use. Available options: database (default) | s3
> NEXT_PUBLIC_UPLOAD_TRANSPORT="s3"
> # OPTIONAL: Defines the endpoint to use for the S3 storage transport. Relevant when using third-party S3-compatible providers.
> NEXT_PRIVATE_UPLOAD_ENDPOINT="https://s3.domain.io"
> # OPTIONAL: Defines the force path style to use for the S3 storage transport. Relevant when using third-party S3-compatible providers.
> # This will change it from using virtual hosts <bucket>.domain.io/<path> to fully qualified paths domain.io/<bucket>/<path>
> NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE="true"
> # OPTIONAL: Defines the region to use for the S3 storage transport. Defaults to us-east-1.
> NEXT_PRIVATE_UPLOAD_REGION="wx-east-1"
> # REQUIRED: Defines the bucket to use for the S3 storage transport.
> NEXT_PRIVATE_UPLOAD_BUCKET="documenso"
> # OPTIONAL: Defines the access key ID to use for the S3 storage transport.
> NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID="random-chars-1"
> # OPTIONAL: Defines the secret access key to use for the S3 storage transport.
> NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY='long-password-5'
> 
> # [[SMTP]]
> # OPTIONAL: Defines the transport to use for sending emails. Available options: smtp-auth (default) | smtp-api | mailchannels
> NEXT_PRIVATE_SMTP_TRANSPORT="smtp-auth"
> # OPTIONAL: Defines the host to use for sending emails.
> NEXT_PRIVATE_SMTP_HOST="mail.domain.io"
> # OPTIONAL: Defines the port to use for sending emails.
> # 465 is not working right now, use STARTTLS on 587 instead
> NEXT_PRIVATE_SMTP_PORT="587"
> # OPTIONAL: Defines the username to use with the SMTP server.
> NEXT_PRIVATE_SMTP_USERNAME="documenso@domain.io"
> # OPTIONAL: Defines the password to use with the SMTP server.
> NEXT_PRIVATE_SMTP_PASSWORD="app-password"
> # OPTIONAL: Defines the API key user to use with the SMTP server.
> NEXT_PRIVATE_SMTP_APIKEY_USER=
> # OPTIONAL: Defines the API key to use with the SMTP server.
> NEXT_PRIVATE_SMTP_APIKEY=
> # OPTIONAL: Defines whether to force the use of TLS.
> #TLS is not working right now, set it to "false" and use STARTTLS
> NEXT_PRIVATE_SMTP_SECURE="false"
> # OPTIONAL: if this is true and NEXT_PRIVATE_SMTP_SECURE is false then TLS is not used even if the server supports STARTTLS extension
> NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS="false"
> # REQUIRED: Defines the sender name to use for the from address.
> NEXT_PRIVATE_SMTP_FROM_NAME="Documenso"
> # REQUIRED: Defines the email address to use as the from address.
> NEXT_PRIVATE_SMTP_FROM_ADDRESS="documenso@domain.io"
> # OPTIONAL: The API key to use for Resend.com
> NEXT_PRIVATE_RESEND_API_KEY=
> # OPTIONAL: The API key to use for MailChannels.
> NEXT_PRIVATE_MAILCHANNELS_API_KEY=
> # OPTIONAL: The endpoint to use for the MailChannels API if using a proxy.
> NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=
> # OPTIONAL: The domain to use for DKIM signing.
> NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=
> # OPTIONAL: The selector to use for DKIM signing.
> NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=
> # OPTIONAL: The private key to use for DKIM signing.
> NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=
> # OPTIONAL: Displays the maximum document upload limit to the user in MBs
> NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=50
> 
> # [[STRIPE]]
> NEXT_PRIVATE_STRIPE_API_KEY=
> NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET=
> NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_MONTHLY_PRICE_ID=
> NEXT_PUBLIC_STRIPE_ENTERPRISE_PLAN_MONTHLY_PRICE_ID=
> 
> # [[BACKGROUND JOBS]]
> NEXT_PRIVATE_JOBS_PROVIDER="local"
> NEXT_PRIVATE_TRIGGER_API_KEY=
> NEXT_PRIVATE_TRIGGER_API_URL=
> NEXT_PRIVATE_INNGEST_EVENT_KEY=
> 
> # [[FEATURES]]
> # OPTIONAL: Leave blank to disable PostHog and feature flags.
> # POSTHOG has to be hosted/exposed at NEXT_PUBLIC_WEBAPP_URL/ingest
> NEXT_PUBLIC_POSTHOG_KEY=""
> # OPTIONAL: Leave blank to disable billing.
> NEXT_PUBLIC_FEATURE_BILLING_ENABLED=
> # OPTIONAL: Leave blank to allow users to signup through /signup page.
> NEXT_PUBLIC_DISABLE_SIGNUP=
> 
> # [[E2E Tests]]
> E2E_TEST_AUTHENTICATE_USERNAME="Test User"
> E2E_TEST_AUTHENTICATE_USER_EMAIL="testuser@mail.com"
> E2E_TEST_AUTHENTICATE_USER_PASSWORD="test_Password123"
> 
> # This is only required for the marketing site
> # [[REDIS]]
> NEXT_PRIVATE_REDIS_URL=
> NEXT_PRIVATE_REDIS_TOKEN=
> ```

I'm made some changes to fit yours, but still getting the same thing.

**Comment by Dvalin21** [comment]
ENV
```
# [[AUTH]]
NEXTAUTH_URL="https://domain.com"
NEXTAUTH_SECRET="secret"

# [[DATABASE]]
POSTGRES_USER="documenso"
POSTGRES_PASSWORD=password"
POSTGRES_DB="documenso"
NEXT_PRIVATE_DATABASE_URL="postgres://documenso:password@documenso-db:5432/documenso"
NEXT_PRIVATE_DIRECT_DATABASE_URL="postgres://documenso:password@documenso-db:5432/documenso"

# [[CRYPTO]]
# Application Key for symmetric encryption and decryption
# REQUIRED: This should be a random string of at least 32 characters
NEXT_PRIVATE_ENCRYPTION_KEY="key"

# REQUIRED: This should be a random string of at least 32 characters
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY="key"

# [[URLS]]
NEXT_PUBLIC_WEBAPP_URL="https://domain.com"
NEXT_PRIVATE_INTERNAL_WEBAPP_URL="hhttps://domain.com"


NEXT_PUBLIC_MARKETING_URL="https://domain-marketing.com"
NEXT_PUBLIC_UPLOAD_TRANSPORT="database"


# [[SIGNING]]
# The transport to use for document signing. Available options: local (default) | gcloud-hsm
NEXT_PRIVATE_SIGNING_TRANSPORT="local"

# OPTIONAL: The passphrase to use for the local file-based signing transport.
NEXT_PRIVATE_SIGNING_PASSPHRASE=phrase

# OPTIONAL: The local file path to the .p12 file to use for the local signing transport.
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=/opt/documenso/certificate.p12

# OPTIONAL: The base64-encoded contents of the .p12 file to use for the local signing transport.
#NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS=/opt/documenso/


# [[SMTP]]
# OPTIONAL: Defines the transport to use for sending emails. Available options: smtp-auth (default)
NEXT_PRIVATE_SMTP_TRANSPORT="smtp-auth"
NEXT_PRIVATE_SMTP_HOST="mail.domain.com"
NEXT_PRIVATE_SMTP_PORT=587
NEXT_PRIVATE_SMTP_USERNAME="me@domain.com"
NEXT_PRIVATE_SMTP_PASSWORD='mypassword'
NEXT_PRIVATE_SMTP_SECURE="false"
# OPTIONAL: if this is true and NEXT_PRIVATE_SMTP_SECURE is false then TLS is not used even if the server supports STARTTLS extension
NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS="false"
# REQUIRED: Defines the sender name to use for the from address.
NEXT_PRIVATE_SMTP_FROM_NAME="Sign"
NEXT_PRIVATE_SMTP_FROM_ADDRESS="noreply@documenso.com"
# OPTIONAL: Displays the maximum document upload limit to the user in MBs
NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=50
NEXT_PRIVATE_JOBS_PROVIDER="local"

# [[FEATURES]]
# OPTIONAL: Leave blank to disable billing.
NEXT_PUBLIC_FEATURE_BILLING_ENABLED=
# OPTIONAL: Leave blank to allow users to signup through /signup page.
NEXT_PUBLIC_DISABLE_SIGNUP=
```

``
services:
  database:
    container_name: documenso-db
    hostname: documenso-db
    env_file: .env
    image: postgres:15
    #    ports:
    #      - "54320"
    #      - "5432"
    expose:
      - "54320"
      - "5432"
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U documenso
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /home/incus/documenso/db:/var/lib/postgresql/data
  documenso:
    container_name: documenso-app
    hostname: documenso-app
    env_file: .env
    image: documenso/documenso:latest
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3089:3000
      - 3001:3001
    volumes:
      - /home/incus/documenso/certificate.p12:/opt/documenso/certificate.p12
networks:
  documenso:
    name: documenso
    driver: bridge
`
``

**Comment by Dvalin21** [comment]
> As far as I know the marketing site is not used for anything, the marketing site is what website https://documen.so shows. I think for the marketing site to be used there needs to be a certain env var and if that is used normal site is not fired up so you would use either one not both in the same container. Currently in my case even documenso-marketing.domain.io resolves to nothing.
> 
> How are you generating your keys? Almost all keys should be different, the only one that repeats is the DB user password you can try generate them with:
> 
> ```
> openssl rand -base64 64
> ```
> 
> Also iirc `NEXT_PUBLIC_POSTHOG_KEY` should be defined with an empty string.
> 
> I recommend you first try using inbucket to see if mails are sent using that, you just have to add the service to the compose file and change the host and port to `documenso-inbucket` and `2500`.
> 
> ```yaml
>   documenso-inbucket:
>     image: inbucket/inbucket
>     container_name: documenso-inbucket
>     ports:
>       - 9000:9000 # webui
>       #- 2500:2500 # smtp
>       #- 1100:1100 # pop3
>     networks:
>       documenso:
>       npm:
> ```

I've made sure all keys were different, but haven't tried the inbucket.

**Comment by tmlmt** [comment]
I had the same error and your conversation here made me try to add a few environment variables, and I finally received the confirmation email. What did the trick for me is to have all three of these variables set to my public url:
```
NEXTAUTH_URL='https://documenso.[redacted].com'
NEXT_PUBLIC_WEBAPP_URL='https://documenso.[redacted].com'
NEXT_PRIVATE_INTERNAL_WEBAPP_URL='https://documenso.[redacted].com'
```

I just had `NEXT_PUBLIC_WEBAPP_URL` before, and strangely enough I was received password reset and password reset success emails, but not the confirmation email...

**Comment by RosaEinhorn** [comment]
Thanks to everyone for helping to solve this issue (at least for me).
One part has been eye-opening to me which is this comment in @parasiteoflife's config:

> # URL used by the web app to request itself (e.g. local background jobs)
> # This can't be localhost:3000, it doesn't work, you have to use the public URL instead.
> NEXT_PRIVATE_INTERNAL_WEBAPP_URL="https://documenso.domain.io"

I was trying to run documenso privately and access it through a tailscale (headscale) network. Hence I set the domains mentioned by @tmlmt to tailscale dns names. Now that I know that documenso calls its API "publicly" I am sure it was not able to resolve those domain names from inside the container (as the container does now know the tailscale dns).

The solution for me was to host documenso publicly (behind my reverse proxy) and set the domain names to publicly reachable domain names. This solved the issue immediately.

**Comment by Dvalin21** [comment]
@parasiteoflife Hey, got it working. Not really sure which part got it to work as for some reason the email came delayed. When I resent the confirmation email, it was instant. With that said, I would recommend all to use @parasiteoflife compose and env as a default template. The documentation on this application still needs work and a little confusing. Oh and I was able to use my gmail to send the confirmation.

**Comment by epheo** [comment]
Changing private endpoint to public didn't do it alone.
Email webhook now works well once I replaced my public endpoint self-signed cert with one from a known Certificate Authority.

As a Documenso administrator I would like to be able to use a private endpoints for emails webhook instead of the public one.

**Comment by xfang2024** [comment]
got the same problem, the logs showed confirmation letters submitted to the endpoint but the never received the letters.
Eligible jobs: [ 'Send Confirmation Email' ]
Submitting job to endpoint: http://localhost:3000/api/jobs/send.signup.confirmation.email/cm380gz2x0000ow34c9ju6ueq
i tried to change the internal web url to the public url, it's still not working.

**Comment by altingrainca** [comment]
Same here. The fogot password email is sent successfully, but the verification email not...

**Comment by etaxi341** [comment]
Any news on this? I can't get it to work... Reset Password works but not the verify Mail

**Comment by etaxi341** [comment]
Wow... I did not think that this would fix it... I have set the 

NEXT_PRIVATE_INTERNAL_WEBAPP_URL="http://localhost:3000" 
to
NEXT_PRIVATE_INTERNAL_WEBAPP_URL="http://<internal docker container ip>:3000"

and now it works

**Comment by kool2zero** [comment]
[Parasite's reply](https://github.com/documenso/documenso/issues/1307#issuecomment-2408477806) worked for me.  One thing that tripped me up for a bit was that I put the port as a number 587 instead of a string "587".

Also, certain hosting providers like host monster, [seem to require the the name option in the transport function](https://github.com/nodemailer/nodemailer/issues/677#issuecomment-2002092310).

You would need to make the change in [mailer.ts](https://github.com/documenso/documenso/blob/main/packages/email/mailer.ts)

Then rerun:
`npm run build:web`

**Comment by lelehier** [comment]
> Wow... I did not think that this would fix it... I have set the
> 
> NEXT_PRIVATE_INTERNAL_WEBAPP_URL="http://localhost:3000" to NEXT_PRIVATE_INTERNAL_WEBAPP_URL="http://[internal docker container ip]:3000"
> 
> and now it works

no way. I just got the confirmation mail. ._.

Thank you <3

**Comment by Dvalin21** [comment]
> > Wow... I did not think that this would fix it... I have set the
> > NEXT_PRIVATE_INTERNAL_WEBAPP_URL="http://localhost:3000" to NEXT_PRIVATE_INTERNAL_WEBAPP_URL="http://[internal docker container ip]:3000"
> > and now it works
> 
> no way. I just got the confirmation mail. ._.
> 
> Thank you <3

Is this in documentation?

**Comment by Novapixel1010** [comment]
If anyone still trying to figure this out I made a post #1763

**Comment by lntrpdx** [comment]
> Wow... I did not think that this would fix it... I have set the
> 
> NEXT_PRIVATE_INTERNAL_WEBAPP_URL="http://localhost:3000" to NEXT_PRIVATE_INTERNAL_WEBAPP_URL="http://[internal docker container ip]:3000"
> 
> and now it works

Adding some additional info for those who are not successful with this change, I figured that it only works with the default PORT set to 3000, if you set the env variable PORT to [custom_port] different than 3000 and set NEXT_PRIVATE_INTERNAL_WEBAPP_URL to http://documenso:[custom_port] , it has not been working for me, reverting back to 3000 worked.

**Comment by ElTimuro** [comment]
- closing since resolved
- looking into improving
