### ISSUE TITLE
Support for Unicode characters in pdf fillable fields

### ISSUE THREAD

**Issue by ExcelsiorEyer** [documenso/documenso#1333]
### Issue Description

Special unicode characters like currency symbols in fillable form fieldsis causing an error in the Api

### Steps to Reproduce

Include special unicode characters in formValues of the generate-document api. If the unicode characters are removed, it works just fine.

### Expected Behavior

When typed manually the pdf accepts those characters and the template should accept that while generating the document

### Current Behavior

`{
  _err: Error: WinAnsi cannot encode "₹" (0x20b9)
      at Encoding.encodeUnicodeCodePoint (/app/node_modules/@pdf-lib/standard-fonts/lib/Encoding.js:23:23)
      at StandardFontEmbedder.encodeTextAsGlyphs (/app/node_modules/pdf-lib/cjs/core/embedders/StandardFontEmbedder.js:88:41)
      at StandardFontEmbedder.encodeText (/app/node_modules/pdf-lib/cjs/core/embedders/StandardFontEmbedder.js:28:27)
      at PDFFont.encodeText (/app/node_modules/pdf-lib/cjs/api/PDFFont.js:37:30)
      at exports.layoutSinglelineText (/app/node_modules/pdf-lib/cjs/api/text/layout.js:197:24)
      at exports.defaultTextFieldAppearanceProvider (/app/node_modules/pdf-lib/cjs/api/form/appearances.js:260:31)
      at PDFTextField.updateWidgetAppearance (/app/node_modules/pdf-lib/cjs/api/form/PDFTextField.js:719:61)
      at PDFTextField.updateAppearances (/app/node_modules/pdf-lib/cjs/api/form/PDFTextField.js:713:18)
      at PDFTextField.defaultUpdateAppearances (/app/node_modules/pdf-lib/cjs/api/form/PDFTextField.js:689:14)
      at PDFForm.updateFieldAppearances (/app/node_modules/pdf-lib/cjs/api/form/PDFForm.js:542:23)
}`

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by ephraimduncan** [comment]
Fixed. The WinAnsi encoding error (`cannot encode ₹`) no longer occurs because custom font embedding via `fontkit` + Noto Sans bypasses `StandardFontEmbedder` entirely. The error stack trace in the issue references the old `pdf-lib` package, not the current `@cantoo/pdf-lib`.
