### ISSUE TITLE
OIDC LOGIN 

### ISSUE THREAD

**Issue by charlyschulte** [documenso/documenso#1342]
### Issue Description

i get the error: Unknown argument `refresh_expires_in`. Available options are marked with ?. 
i think because my refresh token never expires and therefore is 0 

### Expected Behavior

0 should be a valid in refresh_expires_in

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by zvn2060** [comment]
Doesn't this cause by missing field in Prisma schema?
https://github.com/documenso/documenso/blob/b8310237e4589c128970cb0cdaeebd8862acf160/packages/prisma/schema.prisma#L242-L263

I encountered same error, but the `refresh_expires_in` is 1800

**Comment by celevra** [comment]
ok i'm not a next.js or prisma expert, but i've change ext_expires_in to refresh_expires_in because to comment above was 
```
// Stops next-auth from crashing when dealing with AzureAD
```

after the change it goes a step further but only until the next variable

```
documenso-documenso-1  | Invalid `prisma.account.create()` invocation:
documenso-documenso-1  |
documenso-documenso-1  | {
documenso-documenso-1  |   data: {
documenso-documenso-1  |     provider: "oidc",
documenso-documenso-1  |     type: "oauth",
documenso-documenso-1  |     providerAccountId: "ce2f22a9-3651-4041-90c7-2c2c9bf43758",
documenso-documenso-1  |     access_token: "xxx",
documenso-documenso-1  |     expires_at: 1738782434,
documenso-documenso-1  |     refresh_expires_in: 1800,
documenso-documenso-1  |     refresh_token: "xxx",
documenso-documenso-1  |     token_type: "Bearer",
documenso-documenso-1  |     id_token: "xxx",
documenso-documenso-1  |     not-before-policy: 0,
documenso-documenso-1  |     ~~~~~~~~~~~~~~~~~
documenso-documenso-1  |     session_state: "d4518b2a-c36a-40b1-9a1b-bd3c0ebd9775",
documenso-documenso-1  |     scope: "openid profile email",
documenso-documenso-1  |     userId: 3,
documenso-documenso-1  | ?   id?: String,
documenso-documenso-1  | ?   created_at?: Int | Null,
documenso-documenso-1  | ?   user?: UserCreateNestedOneWithoutAccountsInput
documenso-documenso-1  |   }
documenso-documenso-1  | }
documenso-documenso-1  |
documenso-documenso-1  | Unknown argument `not-before-policy`. Available options are marked with ?.
documenso-documenso-1  |     at En (/app/node_modules/@prisma/client/runtime/library.js:116:5888)
documenso-documenso-1  |     at Cn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6516)
documenso-documenso-1  |     at Cn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6206)
documenso-documenso-1  |     at Cn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5926)
documenso-documenso-1  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9968) {
documenso-documenso-1  |   name: 'LinkAccountError',
documenso-documenso-1  |   code: undefined
documenso-documenso-1  | }
```

**Comment by wafelmolt** [comment]
+1. Same issue on my side. However, I guess the first assumption seems quite false to me. It has nothing to do with the value but with prisma validation.

**Comment by celevra** [comment]
If i switch from docker to directly git compile like in the selfhosting documentation the error is gone and oidc works flawless
Could be because of this:
https://github.com/documenso/documenso/issues/1632

**Comment by brotkastn** [comment]
> If i switch from docker to directly git compile like in the selfhosting documentation the error is gone and oidc works flawless Could be because of this: [#1632](https://github.com/documenso/documenso/issues/1632)

I still use docker, however i changed the compose.yml to refer to the 1.9.0 build (which is sadly not tagged):

`  documenso:
    image: documenso/documenso:b9ae27704161908cd409179a73d5f82bf0ad6432
    depends_on:
`

After that change, i can login via keycloak oidc :)

**Comment by ephraimduncan** [comment]
The codebase has migrated from NextAuth to a custom auth implementation using the Arctic OAuth library, which inherently fixes the original problem.
