### ISSUE TITLE
Document Sharing Link Redirects to Homepage

### ISSUE THREAD

**Issue by daallgeier** [documenso/documenso#603]
## Issue Description

Opening a sharing link to a document throws a console error and redirects to documenso.com (example my pledge: https://app.documenso.com/share/sdwlb8c7t1pkvu) 

```
8593596e-8fa50b0cbb75b2d0.js:9 Uncaught Error: Minified React error #419; visit https://reactjs.org/docs/error-decoder.html?invariant=419 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at 8593596e-8fa50b0cbb75b2d0.js:9:63944
    at Qh (8593596e-8fa50b0cbb75b2d0.js:9:64832)
    at rx (8593596e-8fa50b0cbb75b2d0.js:9:120339)
    at Lk (8593596e-8fa50b0cbb75b2d0.js:9:94328)
    at 8593596e-8fa50b0cbb75b2d0.js:9:94150
    at bf (8593596e-8fa50b0cbb75b2d0.js:9:94157)
    at mf (8593596e-8fa50b0cbb75b2d0.js:9:90680)
    at MessagePort.P (499-e5ab349bd0ad5c7b.js:25:1665)
(anonymous) @ 8593596e-8fa50b0cbb75b2d0.js:9
Qh @ 8593596e-8fa50b0cbb75b2d0.js:9
rx @ 8593596e-8fa50b0cbb75b2d0.js:9
Lk @ 8593596e-8fa50b0cbb75b2d0.js:9
(anonymous) @ 8593596e-8fa50b0cbb75b2d0.js:9
bf @ 8593596e-8fa50b0cbb75b2d0.js:9
mf @ 8593596e-8fa50b0cbb75b2d0.js:9
P @ 499-e5ab349bd0ad5c7b.js:25
```

## Steps to Reproduce

1. go to /documents 
2. Click the "share" button (wait for wayyy too long for it to be copied into clipboard)
3. Paste into new (incognito) tab 
4. Get redirected to documenso.com

## Expected Behavior

I expected to see my signed supporter pledge

## Current Behavior

I am seeing the homepage

## Environment

- OS: macOS Sonoma
- Browser: Chrome
- Version: 118

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by mittalsam98** [comment]
I would like to pick this up

**Comment by Mythie** [comment]
G'day, this one while not a bug does pose the question about phrasing. 

Sharing is intended to be used for some minor virality, the intention is that people that have enjoyed the signing experience can share that by receiving a link that'll show that they've signed with Documenso with their signature or name displayed.

<img width="599" alt="image" src="https://github.com/documenso/documenso/assets/13398220/f5a04bee-11cf-434f-bebd-c263a336ea58">

Problem is in the document dashboard this isn't inherently obvious:

<img width="1219" alt="image" src="https://github.com/documenso/documenso/assets/13398220/32c0fe90-5070-4c7c-ac4e-1885f4025b04">

One might assume that sharing could be used to invite a recipient to sign a document which isn't the case, to improve upon this we should use the same sharing dialog that we have elsewhere in the app:

<img width="648" alt="image" src="https://github.com/documenso/documenso/assets/13398220/cb8b66bf-1d13-4786-a1b5-cdcdf7b09311">

One way to do this would be to allow the document share button to take in an optional children prop which will override the dialog trigger if provided.

**Comment by Mythie** [comment]
@mittalsam98 If you're confident you can make these changes I'm happy to assign it to you 🙌

**Comment by daallgeier** [comment]
the "it" in the suggested tweet seems to refer to the document tho.  Could that be rewritten too? 

``` 
I just signed a document with @documenso.  Check them out!

[url]
```

**Comment by Mythie** [comment]
@mittalsam98 giving this to @luckyklyist apologies!

**Comment by luckyklyist** [comment]
Currently, in the dashboard, the UI looks like this for share. 
<img width="1300" alt="Screenshot 2023-11-02 at 10 24 47 AM" src="https://github.com/documenso/documenso/assets/35479077/6420ea5a-80a2-4a8d-a5a7-c98a23fa67ec">
Should I make changes to replace the sharing element here, or is it fine as it is?
<img width="307" alt="Screenshot 2023-11-02 at 10 25 34 AM" src="https://github.com/documenso/documenso/assets/35479077/f5d59dde-4cfd-4131-b7fe-9b0e6f1f92ab">

**Comment by catalinpit** [comment]
This has been improved.
