### ISSUE TITLE
Railway template install failed

### ISSUE THREAD

**Issue by dougkeiller** [documenso/documenso#932]
### Issue Description

500
Internal Server Error.

Log:

Error: Missing DOCUMENSO_ENCRYPTION_KEY or DOCUMENSO_ENCRYPTION_SECONDARY_KEY keys

at 29145 (/app/apps/web/.next/server/chunks/9086.js:1:17850)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 13542 (/app/apps/web/.next/server/chunks/9086.js:1:18516)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 17100 (/app/apps/web/.next/server/chunks/9086.js:1:23594)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 73273 (/app/apps/web/.next/server/chunks/9086.js:1:16923)

at Function.t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at async rk (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:4674)

at async rx (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:5814)

[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {

digest: '2412266872'

}

Error: Missing DOCUMENSO_ENCRYPTION_KEY or DOCUMENSO_ENCRYPTION_SECONDARY_KEY keys

at 29145 (/app/apps/web/.next/server/chunks/9086.js:1:17850)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 13542 (/app/apps/web/.next/server/chunks/9086.js:1:18516)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 71919 (/app/apps/web/.next/server/app/(dashboard)/documents/page.js:1:6821)

at Function.t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at runNextTicks (node:internal/process/task_queues:60:5)

at listOnTimeout (node:internal/timers:538:9)

at process.processTimers (node:internal/timers:512:7)

at async tn (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:220484)

[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {

digest: '453083097'

}

⨯ [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {

digest: '453083097'

}

Error: Missing DOCUMENSO_ENCRYPTION_KEY or DOCUMENSO_ENCRYPTION_SECONDARY_KEY keys

at 29145 (/app/apps/web/.next/server/chunks/9086.js:1:17850)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 13542 (/app/apps/web/.next/server/chunks/9086.js:1:18516)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 17100 (/app/apps/web/.next/server/chunks/9086.js:1:23594)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 73273 (/app/apps/web/.next/server/chunks/9086.js:1:16923)

at Function.t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at async rk (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:4674)

at async rx (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:5814)

[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {

digest: '2412266872'

}

Error: Missing DOCUMENSO_ENCRYPTION_KEY or DOCUMENSO_ENCRYPTION_SECONDARY_KEY keys

at 29145 (/app/apps/web/.next/server/chunks/9086.js:1:17850)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 13542 (/app/apps/web/.next/server/chunks/9086.js:1:18516)

at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at 71919 (/app/apps/web/.next/server/app/(dashboard)/documents/page.js:1:6821)

at Function.t (/app/apps/web/.next/server/webpack-runtime.js:1:143)

at runNextTicks (node:internal/process/task_queues:60:5)

at listOnTimeout (node:internal/timers:538:9)

at process.processTimers (node:internal/timers:512:7)

at async tn (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:220484)

[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {

digest: '453083097'

}

⨯ [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {

digest: '453083097'

}

Error: Missing DOCUMENSO_ENCRYPTION_KEY or DOCUMENSO_ENCRYPTION_SECONDARY_KEY keys

at 29145 (/app/apps/web/.next/server/chunks/9086.js:1:17850)

### Screenshots (optional)

![image](https://github.com/documenso/documenso/assets/128188043/b0d89312-abcc-47e7-9ed4-d445da2388f7)

### Operating System [e.g., Windows 10]

Railway

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by dougkeiller** [comment]
Hi, 

I deleted the Railway server, created a new server and redeployed

Was able to browse to homepage, but then when I attempted to created an account, I received this error. Replicated twice

![image](https://github.com/documenso/documenso/assets/128188043/c581949d-f21f-4708-9a99-aa3422861861)

**Comment by nishikawa7863** [comment]
Same here, doesn't work

**Comment by asxzy** [comment]
```
# [[CRYPTO]]
# Application Key for symmetric encryption and decryption
# REQUIRED: This should be a random string of at least 32 characters
NEXT_PRIVATE_ENCRYPTION_KEY="CAFEBABE"
# REQUIRED: This should be a random string of at least 32 characters
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY="DEADBEEF"
```

add following to your env

**Comment by ephraimduncan** [comment]
Currently, there is a fix here: https://github.com/documenso/documenso/pull/1174

**Comment by ephraimduncan** [comment]
Closing since there has been a lot of changes and the railway template works fine.
